version: '3.8'

services:
  k8s-learning:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: k8s-learning
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kube_config:/root/.kube
      - ./workspace:/workspace
    stdin_open: true
    tty: true
    network_mode: "host"